apiVersion: v1
kind: Service
metadata:
  namespace: moodle
  name: moodle-service
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
  selector:
    app: moodle-frontend